/** @type {import('tailwindcss').Config} */
const token = (name) => `rgb(var(${name}) / <alpha-value>)`;

export default {
  content: ["./apps/web/index.html", "./apps/web/src/**/*.{ts,tsx}", "./packages/design-system/src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: token("--color-background-app"),
        surface: token("--color-background-surface"),
        "surface-bright": token("--color-background-elevated"),
        "surface-dim": token("--color-background-muted"),
        "surface-container-lowest": token("--color-background-elevated"),
        "surface-container-low": token("--color-background-surface"),
        "surface-container": token("--color-background-muted"),
        "surface-container-high": token("--color-border-strong"),
        "surface-container-highest": token("--color-border-default"),
        "surface-variant": token("--color-border-default"),
        outline: token("--color-border-strong"),
        "outline-variant": token("--color-border-default"),
        line: token("--color-border-default"),
        ink: token("--color-text-primary"),
        "on-background": token("--color-text-primary"),
        "on-surface": token("--color-text-primary"),
        "on-surface-variant": token("--color-text-secondary"),
        primary: token("--color-action-primary"),
        "surface-tint": token("--color-action-primary"),
        "on-primary": token("--color-action-primary-foreground"),
        "primary-container": token("--color-background-muted"),
        "on-primary-container": token("--color-text-primary"),
        "primary-fixed": token("--color-background-muted"),
        "primary-fixed-dim": token("--color-border-default"),
        "on-primary-fixed": token("--color-text-primary"),
        "on-primary-fixed-variant": token("--color-text-secondary"),
        secondary: token("--color-action-secondary"),
        "secondary-container": token("--color-background-muted"),
        "on-secondary": token("--color-action-primary-foreground"),
        "on-secondary-container": token("--color-text-primary"),
        "secondary-fixed": token("--color-background-muted"),
        "secondary-fixed-dim": token("--color-border-default"),
        "on-secondary-fixed": token("--color-text-primary"),
        "on-secondary-fixed-variant": token("--color-text-secondary"),
        tertiary: token("--color-status-info"),
        "tertiary-container": token("--color-background-muted"),
        "tertiary-fixed": token("--color-background-muted"),
        "tertiary-fixed-dim": token("--color-border-default"),
        "on-tertiary": token("--color-action-primary-foreground"),
        "on-tertiary-container": token("--color-text-primary"),
        "on-tertiary-fixed": token("--color-text-primary"),
        "on-tertiary-fixed-variant": token("--color-text-secondary"),
        error: token("--color-status-danger"),
        "error-container": token("--color-background-muted"),
        "on-error": token("--color-action-primary-foreground"),
        "on-error-container": token("--color-text-primary"),
        "inverse-surface": token("--color-text-primary"),
        "inverse-on-surface": token("--color-background-app"),
        "inverse-primary": token("--color-background-muted"),
      },
      borderRadius: {
        lg: "0.45rem",
        xl: "0.65rem",
        "2xl": "0.9rem",
      },
      spacing: {
        "sidebar-width": "260px",
        gutter: "1.5rem",
        "max-content-width": "1280px",
      },
      fontFamily: {
        inter: ["Inter", "ui-sans-serif", "system-ui"],
        geist: ["Geist", "ui-sans-serif", "system-ui"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "title-md": ["Inter"],
        "label-md": ["Geist"],
        "label-sm": ["Geist"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "28px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
